### ISSUE TITLE
nix seperate heroku sample app repo

### ISSUE THREAD

**Issue by jgravois** [koopjs/koop-sample-app#2]
the more i think about this, the more i think it might be sufficient/preferable to just get enough information thrown up here to demystify deploying to heroku until we create a flashier website rather than spinning up another repo.

unless anyone else disagrees, i'll plan on PRing here w/ markdown doc that describes the steps to deploy and begin R&D on what would be required to add a `deploy to heroku` button.

**Comment by ngoldman** [comment]
@jgravois agreed, ideally the default koop sample app should be deployable to heroku without too much extra hoopla.

**Comment by chelm** [comment]
@jgravois PR please! This app should be all that's needed to deploy to heroku, just need to add a procfile i think? Though I think the inclusion of `koop-pgcache` in this sample might get in the way.

**Comment by chelm** [comment]
@jgravois PR https://github.com/koopjs/koop-sample-app/pull/3

Basically the goal is clone, npm install, node server - should just work. We could remove pgCache from it as well and run heroku deploys with essentially little work.

**Comment by chelm** [comment]
@jgravois We can probalby close this right? or do we still have work to do here?

**Comment by jgravois** [comment]
i still need to write the doc, but since we all agree it can go here, I'm good.

**Comment by jgravois** [comment]
just a note that it looks for the time being you can't enable PostGIS on your Heroku PostGres database unless you have a production account.... 

https://devcenter.heroku.com/articles/postgis

not sure whether we should press on with documenting configuring it anyway or just hold tight till the functionality makes its way to hobby accounts.

**Comment by ngoldman** [comment]
@jgravois does heroku plan to extend PostGIS support to free tier accounts?

**Comment by jgravois** [comment]
doesn't look like anytime soon
https://twitter.com/leinweber/status/513328223359631361

in the meantime, it looks like you can provision and delete databases for $0.07/hour, so you aren't necessarily on the hook for a $50/month upgrade to play around with it.
http://stackoverflow.com/questions/10808760/options-for-testing-postgresql-postgis-on-heroku
