### ISSUE TITLE
Unable to install on windows

### ISSUE THREAD

**Issue by sirws** [koopjs/koop-sample-app#30]
D:\temp\koop-sample-app>npm install
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\Program Files\nodejs\\node.exe" "D:\Program Files\nodejs
\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! path D:\temp\koop-sample-app\node_modules\koop-socrata\test\fixtures\mi
ssing::views.json
npm ERR! code ENOENT
npm ERR! errno -4058

npm ERR! enoent ENOENT, open 'D:\temp\koop-sample-app\node_modules\koop-socrata\
test\fixtures\missing::views.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     D:\temp\koop-sample-app\npm-debug.log

Heres the last part of the npm_debug log:
53558 verbose rebuildBundles   'terraformer-arcgis-parser',
53558 verbose rebuildBundles   'terraformer-wkt-parser',
53558 verbose rebuildBundles   'winston' ]
53559 info install koop@2.8.6
53560 info postinstall koop@2.8.6
53561 verbose unlock done using C:\Users\smoore\AppData\Roaming\npm-cache_locks\koop-293447cc9958afae.lock for D:\temp\koop-sample-app\node_modules\koop
53562 verbose stack Error: ENOENT, open 'D:\temp\koop-sample-app\node_modules\koop-socrata\test\fixtures\missing::views.json'
53562 verbose stack     at Error (native)
53563 verbose cwd D:\temp\koop-sample-app
53564 error Windows_NT 6.1.7601
53565 error argv "D:\Program Files\nodejs\\node.exe" "D:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install"
53566 error node v0.12.2
53567 error npm  v2.7.4
53568 error path D:\temp\koop-sample-app\node_modules\koop-socrata\test\fixtures\missing::views.json
53569 error code ENOENT
53570 error errno -4058
53571 error enoent ENOENT, open 'D:\temp\koop-sample-app\node_modules\koop-socrata\test\fixtures\missing::views.json'
53571 error enoent This is most likely not a problem with npm itself
53571 error enoent and is related to npm not being able to find a file.
53572 verbose exit [ -4058, true ]

**Comment by sirws** [comment]
I think that missing::views.json is not a valid filename on windows...

**Comment by dmfenton** [comment]
Socrata is no longer included in the sample app
