### ISSUE TITLE
Add explicit instruction to docs for provider set up

### ISSUE THREAD

**Issue by m1ckr1sk** [koopjs/koop-sample-app#35]
When configuring providers with default parameters, such as the Trimet provider, you need to copy the entry from the providers file into the applications config folder otherwise the application will not have any references for the provider to pick up, e.g. trimet config.key parameter not found.

Could an explicit instruction be added to the docs to make this clear?

**Comment by jgravois** [comment]
thanks for the feedback.  i really like the idea of making sure this sample is totally *plug and play* so i put together a PR which comments out `trimet` initially and adds an additional section to the README which explains how to configure it.

can you take a look at #36 and see if it seems sufficient please?
