### ISSUE TITLE
New version of server.js doesn't work with iisnode

### ISSUE THREAD

**Issue by sirws** [koopjs/koop-sample-app#9]
I just installed the latest version of koop-sample-app and put it in my iis server with iisnode.  I get an internal server error.

If I change this line:
http.createServer(app).listen(config.server.port);
to
http.createServer(app).listen(process.env.PORT || config.server.port);

It works.  Is there a reason this was taken out server.js?  It was there before.  Thanks!

**Comment by sirws** [comment]
@chelm Is there any issue updating this in the master so I don't have to modify it every time there is an update?

**Comment by jgravois** [comment]
that should be fine.  can you PR it?  if not, I can.

**Comment by chelm** [comment]
:+1:

**Comment by sirws** [comment]
https://github.com/koopjs/koop-sample-app/pull/10

**Comment by ngoldman** [comment]
`config.server.port` shouldn't be standard anyway as that's something that should be determined at the app (express) level not the middleware (koop) level.

**Comment by chelm** [comment]
@ngoldman yes and its only used at the app level. That can and should be removed in favor of env.PORT - but also do we have apps default to a port? I guess that'd be no different than having the config default to a port, so... word.

**Comment by ngoldman** [comment]
I believe this is resolved, closing. Thanks for the PR @sirws :+1:

**Comment by mhogeweg** [comment]
new to koop/node.js. not seeing http.createServer(app).listen(config.server.port); in the server.js file in the sample app I just cloned. should the [sample app install documentation](https://gist.github.com/sirws/af77f664da000f295f6d) be updated?

**Comment by sirws** [comment]
@mhogeweg I think their fix means you can skip that step.  I would give it a shot without making that fix.  I will try it later myself with the new server.js and make sure it doesn't break anything.  I don't think it will based on looking at it.

**Comment by jgravois** [comment]
we now set the port [here](https://github.com/koopjs/koop-sample-app/blob/master/server.js#L41)
